import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontSize: {
        head4: "40px",
      },
      width: {
        searchBarFull: "600px",
        searchBarLg: "500px",
        searchBarMd: "450px",
        formlg: "712px",
        multipleChoiceCombobox: "685px",
      },
      screens: {
        md: "768px",
        lg: "1024px",
        macbook: "1460px",
        "2xl": "1980px",
        "01": "1080px",
        "02": "1440px",
        "2k": "1920px",
        FHD: "1920px",
        "4k": "2560px",
        desktop: "1460px",
        mobile: "393px",
      },
      boxShadow: {
        "login-form": "0 4px 40px 0 hsla(var(--box-shadow-01))",
        main: "0 2px 5.5px 0 hsla(var(--box-shadow-02))",
        table: "0 5px 14px 0 hsla(var(--box-shadow-03))",
        card: "0 12px 48px -6px hsla(var(--box-shadow-04))",
      },
      dropShadow: {
        "main-button": "0 8px 16px 0 hsla(var(--primary-Red-03))",
        "secondary-button":
          "0 8px 16px 0 hsla(var(--secondary-caribbean-green-main))",
        "delete-button": "0 8px 16px 0 hsla(var(--primary-Red-03))",
      },
      backgroundImage: {
        "gradient-01":
          "linear-gradient(180deg, hsla(var(--gradient-01-start)), hsla(var(--gradient-01-end)))",
        "gradient-02":
          "linear-gradient(90deg, hsla(var(--gradient-02-start)), hsla(var(--gradient-02-end)))",
        "gradient-03":
          "linear-gradient(90deg, hsla(var(--gradient-03-start)), hsla(var(--gradient-03-end)))",
        "gradient-04":
          "linear-gradient(90deg, hsla(var(--gradient-04-start)), hsla(var(--gradient-04-end)))",
        "gradient-05":
          "linear-gradient(180deg, hsla(var(--gradient-05-start)), hsla(var(--gradient-05-end)))",
        "gradient-06":
          "radial-gradient(circle, hsla(var(--gradient-06-start)), hsla(var(--gradient-06-end)))",
      },
      colors: {
        "gradient-02":
          "linear-gradient(90deg, hsla(var(--gradient-02-start)), hsla(var(--gradient-02-end)))",
        main: {
          "primary-Red-main": "hsla(var(--primary-Red-main))",
        },
        primary: {
          "Red-main": "hsla(var(--primary-Red-main))",
          "Red-01": "hsla(var(--primary-Red-01))",
          "Red-02": "hsla(var(--primary-Red-02))",
          "Red-03": "hsla(var(--primary-Red-03))",
          "Red-04": "hsla(var(--primary-Red-04))",
          "Red-05": "hsla(var(--primary-Red-05))",
          "Red-06": "hsla(var(--primary-Red-06))",
          "Red-07": "hsla(var(--primary-Red-07))",
          "Orenge-main": "hsla(var(--primary-Orenge-main))",
          "Orange-1": "hsla(var(--Primary-Orange-1))",
          "Orange-2": "hsla(var(--Primary-Orange-2))",
          "Orange-3": "hsla(var(--Primary-Orange-3))",
          "Orange-4": "hsla(var(--Primary-Orange-4))",
          "Orange-5": "hsla(var(--Primary-Orange-5))",
          "Orange-6": "hsla(var(--Primary-Orange-6))",
        },
        secondary: {
          "caribbean-green-main": "hsla(var(--secondary-caribbean-green-main))",
          "caribbean-green-main-hover":
            "hsla(var(--secondary-caribbean-green-01))",
          "caribbean-green-01": "hsla(var(--secondary-caribbean-green-01))",
          "caribbean-green-02": "hsla(var(--secondary-caribbean-green-02))",
          "caribbean-green-03": "hsla(var(--secondary-caribbean-green-03))",
          "caribbean-green-04": "hsla(var(--secondary-caribbean-green-04))",
          "teal-green-main": "hsla(var(--secondary-teal-green-main))",
          "teal-green-01": "hsla(var(--secondary-teal-green-01))",
          "teal-green-02": "hsla(var(--secondary-teal-green-02))",
          "teal-green-03": "hsla(var(--secondary-teal-green-03))",
          "teal-green-04": "hsla(var(--secondary-teal-green-04))",
          "teal-green-hover": "hsla(var(--secondary-teal-green-hover))",
          "indigo-main": "hsla(var(--secondary-indigo-main))",
          "indigo-01": "hsla(var(--secondary-indigo-01))",
          "indigo-02": "hsla(var(--secondary-indigo-02))",
          "indigo-03": "hsla(var(--secondary-indigo-03))",
          "indigo-04": "hsla(var(--secondary-indigo-04))",
          "indigo-05": "hsla(var(--secondary-indigo-05))",
          "indigo-hover": "hsla(var(--secondary-indigo-hover))",
          "dark-gray-main": "hsla(var(--secondary-dark-gray-main))",
          "dark-gray-01": "hsla(var(--secondary-dark-gray-01))",
          "dark-gray-02": "hsla(var(--secondary-dark-gray-02))",
          "dark-gray-03": "hsla(var(--secondary-dark-gray-03))",
          "dark-gray-04": "hsla(var(--secondary-dark-gray-04))",
          "dark-gray-05": "hsla(var(--secondary-dark-gray-05))",
          "river-bed-main": "hsla(var(--secondary-river-bed-main))",
          "river-bed-01": "hsla(var(--secondary-river-bed-01))",
          "river-bed-04": "hsla(var(--secondary-river-bed-04))",
        },
        neutral: {
          "00": "hsla(var(--neutral-00))",
          "01": "hsla(var(--neutral-01))",
          "02": "hsla(var(--neutral-02))",
          "03": "hsla(var(--neutral-03))",
          "04": "hsla(var(--neutral-04))",
          "05": "hsla(var(--neutral-05))",
          "06": "hsla(var(--neutral-06))",
          "07": "hsla(var(--neutral-07))",
          "08": "hsla(var(--neutral-08))",
          "09": "hsla(var(--neutral-09))",
          "10": "hsla(var(--neutral-10))",
          "11": "hsla(var(--neutral-11))",
          "12": "hsla(var(--neutral-12))",
          "13": "hsla(var(--neutral-13))",
          "14": "hsla(var(--neutral-14))",
          "15": "hsla(var(--neutral-15))",
          "16": "hsla(var(--neutral-16))",
          "17": "hsla(var(--neutral-17))",
        },
        success: {
          "01": "hsla(var(--success-01))",
          "02": "hsla(var(--success-02))",
          "03": "hsla(var(--success-03))",
        },
        process: {
          "01": "hsla(var(--process-01))",
          "02": "hsla(var(--process-02))",
          "03": "hsla(var(--process-03))",
        },
        urgent: {
          "fail-01": "hsla(var(--urgent-fail-01))",
          "fail-02": "hsla(var(--urgent-fail-02))",
          "fail-03": "hsla(var(--urgent-fail-03))",
          "fail-04": "hsla(var(--urgent-fail-04))",
        },
        accept: {
          "01": "hsla(var(--accept-01))",
          "02": "hsla(var(--accept-02))",
          "03": "hsla(var(--accept-03))",
        },
        text: {
          main: "hsla(var(--main))",
          primary600: "hsla(var(--primary-text-600))",
          disable: "hsla(var(--disable-text))",
        },
        toast: {
          "info-border": "hsla(var(--info-border))",
          "info-background": "hsla(var(--info-background))",
          "success-border": "hsla(var(--success-border))",
          "success-background": "hsla(var(--success-background))",
          "warning-border": "hsla(var(--warning-border))",
          "warning-background": "hsla(var(--warning-background))",
          "error-border": "hsla(var(--error-border))",
          "error-background": "hsla(var(--error-background))",
        },
        sidebar: {
          "text-head": "hsla(var(--sidebar-text-head))",
          "user-card": "hsla(var(--sidebar-user-card))",
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
          "-01": "hsl(var(--sidebar-01))",
          "-02": "hsl(var(--sidebar-02))",
        },
        paginate: {
          text: "hsla(var(--gradient-03-start))",
        },
        component: {
          green: "hsla(var(--gradient-02-start))",
        },
        calendar: {
          selected: "hsla(var(--date-selected))",
          "day-text": "hsla(var(--day-text))",
          today: "hsla(var(--today))",
        },
        login: {
          "01": "hsla(var(--gradient-03-start))",
        },
        modal: {
          "01": "hsla(var(--modal))",
          table: "hsla(var(--table))",
        },
        table: {
          textbody: "hsla(var(--text-table))",
          texttitle: "hsla(var(--text-title))",
        },
        status: {
          textyellow: "hsla(var(--status-yellow-text))",
          yellowbackground: "hsla(var(--status-yellow-background))",
          textred: "hsla(var(--status-red-text))",
          redbackground: "hsla(var(--status-red-background))",
          graybackground: "hsla(var(--status-gray-background))",
          bluebackground: "hsla(var(--status-blue-background))",
          bluetext: "hsla(var(--status-blue-text))",
          textgreen: "hsla(var(--status-green-text))",
          greenbackground: "hsla(var(--status-green-background))",
          purplebackground: "hsla(--status-purple-background)",
          textpurple: "hsla(var(--status-purple-text))",
        },
      },
    },
  },
  plugins: [],
} satisfies Config;
